Hafta2/Models/ErrorViewModel.cs
using System;

namespace Hafta2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hafta2/Controllers/HomeController.cs
using Hafta2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hafta2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public string[] Kayit()
        {
            string[] ogr = new string[3];
            return ogr;
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hafta2/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hafta2.Controllers
{
    public class OgrenciController : Controller
    {
        public IActionResult OgrEkle()
        {
            return View();
        }
        public IActionResult OgrList()
        {
            return View();
        }
        [HttpPost]
        public string OgrKaydet(string ogrAd, string ogrSoyad, string ogrNo)
        {
            string message=ogrAd + " " + ogrSoyad + " " + ogrNo + " kaydedildi." ;
            return message;
        }
    }
}

Hafta2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<body>
    <form>

        <label for="fname">Adi:</label><br>
        <input type="text" id="fname" name="fname"><br>
        <label for="lname">Soyadi:</label><br>
        <input type="text" id="lname" name="lname"><br />
        <label for="number">Ogr.No:</label><br>
        <input type="text" id="number" name="number">
        <br /><br />
        <button action = "Kayit">Kayit Ol</button>
    </form>
    
</body>

Hafta2/Views/Ogrenci/Index.cshtml
@*
  
*@
@{
}

Hafta2/Views/Ogrenci/OgrEkle.cshtml
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Öğrenci Ekleme Platformu.</p>
</div>

<body>
    <form method="post" action="../Ogrenci/OgrKaydet">

        <label for="fname">Adi:</label><br>
        <input type="text" id="fname" name="ogrAd"><br>
        <label for="lname">Soyadi:</label><br>
        <input type="text" id="lname" name="ogrSoyad"><br />
        <label for="number">Ogr.No:</label><br>
        <input type="text" id="number" name="ogrNo">
        <br /><br />
        <td colspan="3"><input type="submit" value="Öğrenci Kaydet" /></td>
    </form>

</body>

Hafta2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hafta2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Ogrenci" asp-action="Index">ÖğrenciIslemleri</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="OgrEkle">Öğrenci Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="OgrList">Öğrenci Listele</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Hafta2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>